### ISSUE TITLE
No button appears

### ISSUE THREAD

**Issue by kurt1984** [damianavila/RISE#137] opened 2015-08-14 17:26 UTC
Hi, I really like this add-on, however I cannot install it correctly.

git clone https://github.com/damianavila/RISE.git
python setup.py install 

after that run Jupyter, the cell toolbar has slideshow option.

**Comment by sboisen** [comment] 2015-08-14 18:25
My issue may be the same. I've installed the latest version of Jupyter (http://blog.jupyter.org/2015/08/12/first-release-of-jupyter/). Then i did:

* git clone https://github.com/damianavila/RISE.git
* cd RISE
* python setup.py install

There was a long sequence of messages like

    copying /Users/sboisen/git/etc/jupyter/RISE/livereveal/main.css -> /Users/sboisen/Library/Jupyter/nbextensions/livereveal/main.css

so it appeared to succeed. 

Then i run

    jupyter notebook

but there's no button to *start* a slideshow (neither FireFox nor Chrome). The Cell Toolbar menu does have a Slideshow option, and it does what it should (I've used this with iPython v3 so i know how it's *supposed* to work). But how do i launch the Reveal.js presentation mode?

**Comment by damianavila** [comment] 2015-08-15 15:12
You are probably hit by an upstream bug on Jupyter. Check this issue: https://github.com/damianavila/RISE/issues/136 for a temporary workaround until the next release of the notebook is out... let me know if that does not help.

**Comment by damianavila** [comment] 2016-07-11 22:31
Tested master with latest notebook 4.2.1 and buttons appear OK. 
So closing here. Feel free to re-open to add more info or if you see issue again.

**Closed by damianavila** 2016-07-11 22:31 UTC
Labels: wontfix

**Comment by zizzipupp** [comment] 2017-05-18 08:34
Hi, I have just installed RISE and have rebooted Jupyter. However, no button appears. My IPython Jupyter version is 5.1.0

**Comment by damianavila** [comment] 2017-05-18 13:21
Can you post the output of this command: `jupyter nbextension list`
Maybe it is a cache issue, did you hard-reload the page: https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.WR2f1N_6y00

Thanks.

**Comment by zizzipupp** [comment] 2017-05-18 13:31
Hi Damian,

thank you for your message. I have just figured out that I had not properly
installed RISE. After typing conda install -c damianavila82 rise it worked
like a charm!

Again, thanks!
Francesco

**Comment by damianavila** [comment] 2017-05-19 20:26
>Again, thanks!

Great, thanks to you!

**Comment by snowCbrands** [comment] 2017-08-09 17:04
Hi Damian, 

I had download the rise on conda, but when I open the jupyter notebook, the button doesn't show up. Would you please help?

Thanks

**Comment by damianavila** [comment] 2017-08-10 13:29
@snowCbrands what's the `jupyter nbextension list`? Do you have any error in the js console? What's your `conda list rise`?

**Comment by snowCbrands** [comment] 2017-08-10 14:05
Thank you Damian. I'm sorry that I'm not really familiar with the terms. Basically, I read and followed your instruction. 
Option 1 - Using conda (recommended):
conda install -c damianavila82 rise                (I tried this one on conda run, but after install it, the button doesn't show up. I tried to install it again, but it shows that all the packages already exist.  )


Option 2 - Using pip (less recommended):
pip install RISE                                 (Successful)
and then two more steps to install the JS and CSS in the proper places:
jupyter-nbextension install rise --py --sys-prefix                         (the notebook runs forever)
and enable the nbextension:
jupyter-nbextension enable rise --py --sys-prefix                        (the notebook runs forever)

I don't know if this is clear enough for you to help... If not, that's fine! I can use my friend's laptop to do it because he just use the Option 1 and installed successfully(we have the same laptops). 

Thanks

**Comment by damianavila** [comment] 2017-08-10 15:33
If you run the command I request above in your machine we can have some info to know what is happening and why you are not seeing the button.

**Comment by snowCbrands** [comment] 2017-08-10 16:06
Thanks Damian, 

After running jupyter nbextension list, I got:
notebook section
    rice/main enabled
    - Validating: ok

After running conda list rise, I got:
rise                5.0.0            py36_0    damianavila82

Is this what you are trying to see? I'm sorry for the trouble! 

Thanks

**Comment by snowCbrands** [comment] 2017-08-10 16:07
Thanks Damian,

After running jupyter nbextension list, I got:
notebook section
rise/main enabled
- Validating: ok

After running conda list rise, I got:
rise 5.0.0 py36_0 damianavila82

Is this what you are trying to see? I'm sorry for the trouble!

Thanks

**Comment by damianavila** [comment] 2017-08-11 00:16
OK, can you ask you more info?

`jupyter --paths`

After knowing that I can give you other command to explore if everything is in place (or not).

As I said before, do you see any error in the js console (https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers).

**Comment by DanBoardman** [comment] 2017-12-08 01:13
I'm not seeing a solve for this. Is there another issue still open?

I've got the same problem.
Seeing the questions asked I found the following info, though it means very little to me. Any help?


**> jupyter nbextension list**
Known nbextensions:
  config dir: C:\Users\boardmand\AppData\Local\Continuum\anaconda3\etc\jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: ok
      rise/main enabled
      - Validating: ok

**> conda list rise**
# packages in environment at C:\Users\boardmand\AppData\Local\Continuum\anaconda3:
#
rise                      5.1.0                    py36_1    damianavila82

**> jupyter --paths**
config:
    C:\Users\boardmand\.jupyter
    C:\Users\boardmand\AppData\Local\Continuum\anaconda3\etc\jupyter
    C:\ProgramData\jupyter
data:
    C:\Users\boardmand\AppData\Roaming\jupyter
    C:\Users\boardmand\AppData\Local\Continuum\anaconda3\share\jupyter
    C:\ProgramData\jupyter
runtime:
    C:\Users\boardmand\AppData\Roaming\jupyter\runtime

**Comment by damianavila** [comment] 2017-12-08 12:19
Do you have any output in the JS console?

**Comment by DanBoardman** [comment] 2017-12-08 20:13
@damianavila 

Sorry to bother you. Between the multiple security environments and browsers I use, I've found one combo that works. Must be something esoteric.

**Comment by hyperbah** [comment] 2018-02-06 15:17
Hi @damianavila, 
I have the same problem as mentioned above. Here are my outputs, including the one in the JS console: 

**conda list rise**
```
# packages in environment at /home/hipperta/anaconda2:
#
# Name                    Version                   Build  Channel
rise                      5.2.0                    py27_0    damianavila82

```
**jupyter --paths**
```
config:
    /home/hipperta/.jupyter
    /home/hipperta/anaconda2/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/hipperta/.local/share/jupyter
    /home/hipperta/anaconda2/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /run/user/1000/jupyter
```
**jupyter nbextension list**
```
Known nbextensions:
  config dir: /home/hipperta/anaconda2/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      rise/main  enabled 
      - Validating: OK
```

Here is the output in the JS console :

```
L’utilisation de « getPreventDefault() » est obsolète. Utiliser « defaultPrevented » à la place.
jquery.min.js:5
L’utilisation des « Mutation Events » est obsolète. Utiliser « MutationObserver » à la place.
jquery.min.js:5
actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
menubar.js:303
accessing "actions" on the global IPython/Jupyter is not recommended. Pass it to your objects contructors at creation time
main.js:201
load_extensions 
Arguments { 0: "jupyter-js-widgets/extension", 1: "rise/main", … }
utils.js:60
Session: kernel_created (6c706834-f79e-4a0a-bfac-3a5e81bd361f)
session.js:54
Starting WebSockets: ws://localhost:8888/api/kernels/4726e370-5f9d-406d-9273-e2a710c893fe
kernel.js:459
Loading extension: jupyter-js-widgets/extension
utils.js:37
Loading extension: rise/main
utils.js:37
TypeError: action is undefined
Stack trace:
ToolBar.prototype.add_buttons_group/<@http://localhost:8888/static/notebook/js/main.min.js?v=6a166b31c5a20f809e44ec2d50e40412:32406:1
ToolBar.prototype.add_buttons_group@http://localhost:8888/static/notebook/js/main.min.js?v=6a166b31c5a20f809e44ec2d50e40412:32395:14
setup@http://localhost:8888/nbextensions/rise/main.js?v=20180206155340:953:5
load_extension/</<@http://localhost:8888/static/notebook/js/main.min.js?v=6a166b31c5a20f809e44ec2d50e40412:12408:41
execCb@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1690:24
check@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:865:43
enable/</<@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1140:29
bind/<@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:131:20
emit/<@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1190:21
each@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:56:31
emit@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1189:17
check@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:940:25
enable@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1177:17
init@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:783:21
callGetModule@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1204:17
completeLoad@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1583:21
onScriptLoad@http://localhost:8888/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1711:21
require.js:900:37
Kernel: kernel_connected (4726e370-5f9d-406d-9273-e2a710c893fe)
kernel.js:103
Kernel: kernel_ready (4726e370-5f9d-406d-9273-e2a710c893fe)
kernel.js:103
```

**Comment by damianavila** [comment] 2018-02-06 15:52
@hyperbah 

Some questions:

* notebook version?
* browser version?
* can you try hard-reloading your browser (some info here: https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.Wnmm25M-dhE, to get rid of the cache)?
* can you try installing in a new environment without other extensions to get rid of possible interferences?

Thanks!

**Comment by hyperbah** [comment] 2018-02-06 16:14
- notebook version : 5.0.0

- browser version : firefox quantum 58.0.1

- I tried hard-reloading but it doesn't work

- I installed a new environment with python 3 and it works fine now ! My previous try was based on python 2.7 which is installed on my machine, but I don't see why it wouldn't work this way.

Thanks for your help

**Comment by damianavila** [comment] 2018-02-06 16:24
> I installed a new environment with python 3 and it works fine now ! 

Good to know!

> My previous try was based on python 2.7 which is installed on my machine, but I don't see why it wouldn't work this way.

Weird, it should work as well... do you have any other extension in that python 2.7 environment?

**Comment by ahippert** [comment] 2018-02-06 16:51
I was working with the anaconda base, which was using python 2.7. I had no environment installed.

**Comment by damianavila** [comment] 2018-02-06 17:07
Thanks for the additional info... weird, as I said.

**Comment by sailngarbwm** [comment] 2018-02-08 05:28
@damianavila  I just installed rise and am having similar issues, I checked all the stuff in the command line above, but got this javascript error when loading a Jupyter notebook (see below) and am not sure what is going on, 

I am on a windows 7 (64 bit) machine, using Python 3.6, rise 5.5.2 and Chrome Version 64.0.3282.140 (Official Build) (64-bit)

Cheers,

Jon

I am getting the following error in the Javascript console:

actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
MenuBar.bind_events @ menubar.js:303
utils.js:60 load_extensions Arguments(2)
utils.js:37 Loading extension: rise/main
require.js?v=6da8be361b9ee26c5e721e76c6d4afce:900 TypeError: Cannot read property 'help' of undefined
    at toolbar.js:101
    at MainToolBar.ToolBar.add_buttons_group (toolbar.js:115)
    at Function.setup [as load_ipython_extension] (main.js?v=20180208161927:953)
    at utils.js:39
    at Object.execCb (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1690)
    at Module.check (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:865)
    at Module.<anonymous> (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1140)
    at require.js?v=6da8be361b9ee26c5e721e76c6d4afce:131
    at require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1190
    at each (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:56)
check @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:900
session.js:54 Session: kernel_created (209702de-a1b5-40fc-8a61-1f2addde9f4c)
kernel.js:459 Starting WebSockets: ws://localhost:8888/api/kernels/6c4535e3-392c-4f61-86dd-be09964c7d83
utils.js:37 Loading extension: jupyter-js-widgets/extension
kernel.js:103 Kernel: kernel_connected (6c4535e3-392c-4f61-86dd-be09964c7d83)
kernel.js:103 Kernel: kernel_ready (6c4535e3-392c-4f61-86dd-be09964c7d83)

**Comment by damianavila** [comment] 2018-02-08 11:27
@sailngarbwm did you try this?

> can you try installing in a new environment without other extensions to get rid of possible interferences?

Do you still see the error?
Do you have something in ~/.jupyter/custom/custom.js (what's the output of `jupyter --paths`?

**Comment by sailngarbwm** [comment] 2018-02-08 23:09
@damianavila 

Yeah creating a fresh environment worked. thanks!

**Comment by dkapitan** [comment] 2018-03-02 06:27
Hi @damianavila, having similar issue and getting an js error running on:

- OS X High Sierra (10.3.3)
- conda 4.3
- python 3.6
- Chrome 64.0.3282.186 (Official Build) (64-bit).

Any suggestion would be appreciated!

```
main.min.js:33264 actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
MenuBar.bind_events @ main.min.js:33264
main.min.js:12429 load_extensions Arguments(2)0: "jupyter-js-widgets/extension"1: "rise/main"callee: (...)length: 2Symbol(Symbol.iterator): ƒ values()get callee: ƒ ()set callee: ƒ ()__proto__: Object
(unknown) Bokeh: BokehJS not loaded, scheduling load and callback at Fri Mar 02 2018 07:10:43 GMT+0100 (CET)
(unknown) Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.js
(unknown) Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.13.min.js
(unknown) Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-tables-0.12.13.min.js
(unknown) Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/release/bokeh-gl-0.12.13.min.js
main.min.js:24777 Session: kernel_created (6152ec28-46f5-4d6e-b0d5-13b8b2a25a67)
main.min.js:23933 Starting WebSockets: ws://localhost:8888/api/kernels/20ac498d-b4b0-4844-afd0-2f207e9d9ad7
main.min.js:12406 Loading extension: rise/main
require.js:900 TypeError: Cannot read property 'help' of undefined
    at main.min.js:32406
    at MainToolBar.ToolBar.add_buttons_group (main.min.js:32420)
    at Function.setup [as load_ipython_extension] (:8888/nbextensions/rise/main.js?v=20180302071001:953)
    at main.min.js:12408
    at Object.execCb (require.js:1690)
    at Module.check (require.js:865)
    at Module.<anonymous> (require.js:1140)
    at require.js:131
    at require.js:1190
    at each (require.js:56)
check @ require.js:900
main.min.js:23577 Kernel: kernel_connected (20ac498d-b4b0-4844-afd0-2f207e9d9ad7)
main.min.js:23577 Kernel: kernel_ready (20ac498d-b4b0-4844-afd0-2f207e9d9ad7)
(unknown) Bokeh: all BokehJS libraries loaded
(unknown) Bokeh: BokehJS plotting callback run at Fri Mar 02 2018 07:10:43 GMT+0100 (CET)
cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.js:1 [bokeh] setting log level to: 'info'
(unknown) Bokeh: injecting CSS: https://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.css
(unknown) Bokeh: injecting CSS: https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.13.min.css
(unknown) Bokeh: injecting CSS: https://cdn.pydata.org/bokeh/release/bokeh-tables-0.12.13.min.css
(unknown) Bokeh: all callbacks have finished
cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.js:1 [bokeh] document idle at 39 ms
main.min.js:12406 Loading extension: jupyter-js-widgets/extension
```


This is my jupyter install:
```
jupyter                   1.0.0            py36h598a6cc_0
jupyter-core              4.4.0                     <pip>
jupyter_client            5.1.0            py36hf6c435f_0
jupyter_console           5.2.0            py36hccf5b1c_1
jupyter_core              4.3.0            py36h93810fe_0
jupyterlab                0.31.8                   py36_1    conda-forge
jupyterlab_launcher       0.10.2                   py36_0    conda-forge
jupyterthemes             0.18.5                    <pip>
``

jupyter --paths:
```
config:
    /Users/dkapitan/.jupyter
    /Users/dkapitan/anaconda3/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/dkapitan/Library/Jupyter
    /Users/dkapitan/anaconda3/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/dkapitan/Library/Jupyter/runtime
```
jupyter extension list
```
Known nbextensions:
  config dir: /Users/dkapitan/anaconda3/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
      rise/main  enabled
      - Validating: OK
```

**Comment by damianavila** [comment] 2018-03-02 11:44
@dkapitan, what is your notebook version?

`conda list notebook`

Can you try upgrading to the latest and check if that solves the issue?

**Comment by dkapitan** [comment] 2018-03-02 23:18
@damianavila 
yes, thank you: was running `notebook 5.0.0`. Updated to `5.4.0` and works like a charm!
+1!

**Comment by RZachLamberty** [comment] 2018-08-30 03:59
@damianavila 

I believe I can reliably reproduce this bug. I believe it occurs when the installation of `rise` via `conda` fails to complete because of a *currently running* `jupyter notebook` session in that `conda` environment.

I happened to find myself struggling with this again today and returned to my notebook server only to find it was spitting out error messages about an inability to locate `libsodium`. I realized after this that although `rise` was listed as an installed package (further `conda install` statements do nothing), it *was not* listed as a known extension. uninstall and then reinstall *continued* to fail as long as a server was running, and worked exactly as expected when the server was not.

obviously this is specifically how you are *supposed* to work with `conda` environments, but given that it often works even when users abuse it, I've picked up that bad habit (and assume many others have as well)

**Comment by damianavila** [comment] 2018-09-04 19:48
@RZachLamberty, thanks for the detailed description (and investigation)! I have labeled this as docs so we can surface this info a little bit more.

**Comment by ngolin** [comment] 2019-07-17 15:04
In summary:
```bash
pip3 install --upgrade --force-reinstall --no-cache-dir jupyter
pip3 install --upgrade --force-reinstall --no-cache-dir RISE

sudo -E env "PATH=$PATH" jupyter-nbextension install rise --py
sudo -E env "PATH=$PATH" jupyter-nbextension enable rise --py

jupyter nbextension list

jupyter notebook --no-browser
```

**Comment by damianavila** [comment] 2019-07-17 15:10
@ngolin these are the steps to reproduce the issue in your case?

**Comment by ngolin** [comment] 2019-07-17 17:08
@damianavila Actually it's to solve the issue in my case. It seems the installation has messed up somehow. `--force-reinstall` does the trick.

**Comment by damianavila** [comment] 2019-07-17 18:51
OK, you should probably be OK with the first 2 lines because the latest versions of RISE does not need post-installation steps to enable it.
Btw, thanks for the comment!

**Comment by SMZ70** [comment] 2019-10-05 19:02
Hi. I have the same problem. I even tried reinstalling Conda but didn't work. I upgraded both notebook and rise using:
conda upgrade
This one also didn't work. Still, I don't see the button

**Comment by parmentelat** [comment] 2019-10-06 08:01
Hi

A bug has been fixed relatively recently that could explain this sort of behavior. 
I can’t seem to find its number from my iphone but in essence it was triggering because a keyboard shortcut was assigned by another extension, and that caused RISE’s initialization code to bail out

Checking the contents of the browser console could help confirm that

One way to install a version that may fix the issue for you would be

`pip install -U —pre rise`

However I am very unfamiliar with conda and don’t know how to deal with that aspect of your setup

**Comment by damianavila** [comment] 2019-11-08 13:00
@SMZ70 it would be nice to have the conda list from the environment where you have RISE installed to try to reproduce the issue. 

Suggestions provided by @parmentelat will help you as well.

**Comment by Saho12** [comment] 2020-05-09 13:00
Can anyone help me on this 
https://github.com/damianavila/RISE/issues/420#issuecomment-626047346

**Comment by gguibon** [comment] 2020-09-15 13:22
Followed the summary provided by @ngolin https://github.com/damianavila/RISE/issues/137#issuecomment-512295955.
Worked like a charm thank you.
(issue was on pip3 with any browser -chrome opera firefox-)

**Comment by Eddy-Morgan** [comment] 2022-10-13 21:58
> In summary:
> 
> ```shell
> pip3 install --upgrade --force-reinstall --no-cache-dir jupyter
> pip3 install --upgrade --force-reinstall --no-cache-dir RISE
> 
> sudo -E env "PATH=$PATH" jupyter-nbextension install rise --py
> sudo -E env "PATH=$PATH" jupyter-nbextension enable rise --py
> 
> jupyter nbextension list
> 
> jupyter notebook --no-browser
> ```

this worked for me
