### ISSUE TITLE
liverreveal CSS location

### ISSUE THREAD

**Issue by LuisSoares** [damianavila/RISE#161] opened 2015-10-21 12:37 UTC
Hi Damian,

First congratulation on the great tools.

I have a problem finding the CSS files for the livereveal, I am working on a windows machine and ever since the migration from Ipython to Jupyter there seems to be a bunch of directories that contain the code for the reveal.js used on the notebooks therefore I don't know which instance of the code is being used by RISE. Do you happen to know a way to know which files are being used in the Jupyter notebook, I would like to modify the CSS since there are some differences in the markdown header sizes between the live slides and the ones built by the nbconvert tool.

Thanks
Luis

**Comment by mjbright** [comment] 2015-10-21 12:51
Hi,

On my Windows 8, the reveal.js files are here:

/C/Users/mjbright/AppData/Roaming/jupyter/nbextensions/livereveal/reveal.js

Hope that helps,
Mike.

**Comment by LuisSoares** [comment] 2015-10-21 13:27
Hi Mike

Thanks for the help. You are right the livereveal files are in that folder (I checked and deleting it removes the extension). I still have the problem that changing the CSS for a specific theme does not seem to change the display, I'll have to look further in how to customize the theme CSS.
Thanks,
Luis

**Comment by damianavila** [comment] 2015-10-26 19:39
@LuisSoares, you prbably need to modify this file for further customization: https://github.com/damianavila/RISE/blob/master/src/less/main.less and recreate the css file as described here: https://github.com/damianavila/RISE#development

It could be some issues when you try to modify reveal specific things... let me know if you get stucked...

**Comment by wiso** [comment] 2016-01-06 00:04
Hello, I have the exact same problem. I have added a file `custom.css` in the same folder as the ipynb file. Is has no effect. If I open the notebook in the presentation mode and I look at the generated HTML I see:

    <link rel="stylesheet" href="/custom/custom.css" type="text/css">

the problem is the "/" (actually the problem is also `/custom`, but this can be solved creating a directory). If I change (using the developer tool of chrome) the line to:

    <link rel="stylesheet" href="custom.css" type="text/css">

or to

       <link rel="stylesheet" href="custom/custom.css" type="text/css">

but this time creating a directory `custom`, it works.

Maybe this problem is related to this other I get:

     jupyter nbconvert Lecture1.ipynb --to slides --post serve

```
[NbConvertApp] WARNING | Collisions detected in jupyter_nbconvert_config.py and jupyter_nbconvert_config.json config files. jupyter_nbconvert_config.json has higher priority: {
  "Exporter": {
    "template_path": "['.', '/home/turra/.local/share/jupyter/templates'] ignored, using [u'/home/turra/.local/share/jupyter/templates']"
  }
}
```

**Comment by jason-s** [comment] 2016-07-09 00:22
Same issue here. It would be nice if it looked for two CSS files:

- a fixed-name file in the same directory as the .ipynb file (`RISE-custom.css` or `slideshow.css`: I think `custom.css` is too generic)
- a file that is the same name, and same directory, as the .ipynb file but with .css (so if you have `foo.ipynb` it looks for `foo.css`)

**Comment by damianavila** [comment] 2016-07-11 21:44
Previous discussion lives here: https://github.com/damianavila/RISE/issues/95
Closing this one because the original question was answered.
We can continue any further discussion in #95

**Closed by damianavila** 2016-07-11 21:44 UTC
Labels: discussion

**Comment by damianavila** [comment] 2016-07-11 21:46
@wiso, I just want to tell you that you are trying to customize css with the nbconvert slideshows and this is RISE, not the slides exporter in nbconvert. Cheers.
