### ISSUE TITLE
Up-/down-arrow navigation does not work in slideshow

### ISSUE THREAD

**Issue by ThomasA** [damianavila/RISE#91] opened 2015-03-31 12:39 UTC
I have just tested RISE with IPython 3.0.0 and RISE cloned from commit d0a8fbd0d6355f6a9516fb9ecc6bdbdedd6b6e56. When I create a simple slideshow with a couple of slides and some sub-slides or fragments on the first slide, I cannot navigate between sub-slides or fragments using the up/down keys. Left/right keys work fine for navigating between slides. I have previously opened a static reveal slideshow where up/down worked just fine, so I expected that here as well. Is this a known issue?

I am using Firefox 36.0.4 on Linux. I have also tried starting IPython notebook with Chromium as browser, but that does not seem to work at all...

**Comment by damianavila** [comment] 2015-03-31 16:07
Up and down and not working in RISE by design... they conflict with the up/down actions in the notebook itself... so in RISE to go up/down you have to use pgup/pgdown or you can alternativate go forward/backward with spacebar/shift+spacebar.
If you click on the question mark, you will see the shortcuts used by RISE.

Cheers.

**Comment by damianavila** [comment] 2015-03-31 16:08
Maybe we can do a note in the README, PR accepted ;-)

**Comment by ThomasA** [comment] 2015-03-31 21:52
Thanks for clarifying.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by damianavila** [comment] 2015-08-02 18:54
This info is already mentioned in the README, closing here.

**Closed by damianavila** 2015-08-02 18:54 UTC
Labels: docs
