### ISSUE TITLE
Hiding Python code but not the output

### ISSUE THREAD

**Issue by tschm** [damianavila/RISE#150] opened 2015-10-08 07:33 UTC
Hi, I want to hide some of the Python used to produce a graph but not the graph. Is there a way to achieve this?
thomas

**Comment by debsankha** [comment] 2015-10-08 09:24
There is an IPython notebook plugin for that:
https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Hide-Input-All

**Comment by guidov** [comment] 2015-10-08 14:55
This is also an very nice extension for this purpose and is easy to install:
https://github.com/kirbs-/hide_code

**Comment by damianavila** [comment] 2015-10-09 11:44
Additionally, the hide functionality seems to be finally approaching the notebook in the future... ref: https://github.com/jupyter/notebook/issues/534

Closing as duplicate of #32

**Closed by damianavila** 2015-10-09 11:44 UTC
