### ISSUE TITLE
Configuring theme in 4.0.0b1 resets after a single view

### ISSUE THREAD

**Issue by chasehere** [damianavila/RISE#225] opened 2016-09-09 20:14 UTC
I am able to change the theme with the following 

```
from traitlets.config.manager import BaseJSONConfigManager
path = "/home/damian/miniconda3/envs/rise_latest/etc/jupyter/nbconfig"
cm = BaseJSONConfigManager(config_dir=path)
cm.update('livereveal', {
              'theme': 'sky',
              'transition': 'zoom',
              'start_slideshow_at': 'selected',
})
```

The first time I view the slideshow I see it uses the sky.css.  If I do not reload the page, then every subsequent slideshow view reverts back to simple.css.  I would like to be able to exit/enter slideshow mode without having to reload the page each time.

**Comment by damianavila** [comment] 2016-09-12 13:22
>If I do not reload the page, then every subsequent slideshow view reverts back to simple.css.

You mean: the first time it uses the sky theme, then you exit the slideshow mode and when you enter again, you don't see the sky theme anymore? Weird...

Can you post the ipynb file to check? Thanks!

**Comment by chasehere** [comment] 2016-09-12 17:08
> You mean: the first time it uses the sky theme, then you exit the slideshow mode and when you enter again, you don't see the sky theme anymore? Weird...

Correct, but I'm having trouble reproducing the issue today.  Now I can't get it off sky even if I change the theme to something else.  

Here is the notebook:
https://github.com/chasehere/Config/blob/master/RISE%20Issue%20%23225.ipynb

**Comment by damianavila** [comment] 2016-09-13 12:13
Some more questions: are you using RISE master? or the published beta? and what is your notebook version? Thanks again.

**Comment by chasehere** [comment] 2016-09-13 13:44
My notebook version is 4.2.1.  I'm not sure which RISE I am using, how would I find out?  I did the
```
conda install -c damianavila82 rise
```

**Comment by damianavila** [comment] 2016-09-13 16:47
ok, that's the last one and the only version available as a conda package... btw, you can see the version with just `conda list rise` and check the output... or alternative in a python/ipython console:

```python
import rise
rise.__version__
```

**Comment by jccardonar** [comment] 2017-05-16 22:48
Is this issue still relevant? I am also experiencing it.
Rise '4.0.0b1'
Jupyter 4.3.0
Python 3.6 (installed using pip; since conda did not work)

**Comment by damianavila** [comment] 2017-05-18 13:24
> Is this issue still relevant? I am also experiencing it.

I am not seeing in latest notebook 5. Can you check with the notebook updated? Tha

**Comment by jccardonar** [comment] 2017-05-18 14:23
Sorry Damian, yes, jupyter core is 4.3.0, jupyter notebook version is 5.0.0. I guess must be something local since you cannot reproduce.

**Comment by damianavila** [comment] 2017-05-19 20:27
@jccardonar is too much to ask you to test https://github.com/damianavila/RISE/pull/258 and see if you see the same behavior... Feel free to say no :wink:

**Comment by jccardonar** [comment] 2017-05-19 20:50
Sure! Give me a couple of days, please (have a presentation soon and don't want to change too much before it).

**Comment by damianavila** [comment] 2017-05-20 01:07
> Give me a couple of days, please (have a presentation soon and don't want to change too much before it).

Of course!

**Comment by jccardonar** [comment] 2017-05-23 12:34
Retried after manually installing the  version in master.
However, I am still not getting the theme after entering the slides for a second time (works fine the first time). 

By the way, 'start_slideshow_at': 'selected' was not working before for me, and now it is.

I don't find this issue so relevant, but I will be happy of doing any tests  you need me to.

**Comment by damianavila** [comment] 2017-05-24 13:05
> However, I am still not getting the theme after entering the slides for a second time (works fine the first time).

Which is weird, why is not working the second time??? Which platform and browser are you?

> By the way, 'start_slideshow_at': 'selected' was not working before for me, and now it is.

Some good news!

**Comment by jccardonar** [comment] 2017-05-26 13:47
Mac/Firefox... I tried it over Chrome and it works properly there...

**Comment by damianavila** [comment] 2017-05-29 12:25
> Mac/Firefox... I tried it over Chrome and it works properly there...

Ohh... browser specific stuff... interesting. Which Firefox version are you using?

**Comment by jccardonar** [comment] 2017-06-03 15:04
Ok, rechecked again after updating and still not working in Firefox: 53.0.3 (64-bit)
It works consistently in Chrome (58.0.3029)

**Comment by damianavila** [comment] 2017-06-04 17:44
> Ok, rechecked again after updating and still not working in Firefox: 53.0.3 (64-bit)
> It works consistently in Chrome (58.0.3029)

Thanks for trying... I have the very same version of Chrome and Firefox and it is working for me in both.
Do you have maybe some kind of extension in firefox? That could potentially affect the RISE behavior? Can you try in incognito mode (I think that will disable any interfere if it is there).

**Comment by jccardonar** [comment] 2017-06-04 17:50
Disabling the plugins (safe mode) indeed solved the issue. I apologize for not trying that before!

**Comment by damianavila** [comment] 2017-06-04 18:05
> Disabling the plugins (safe mode) indeed solved the issue. I apologize for not trying that before!

Glad we found it! Do you know which extension is causing your issues? So we can add the note at the README, then other people do not have to get into the same issue as you.

**Comment by jccardonar** [comment] 2017-06-05 09:16
Sure! Give me a few days though, I need to experiment to be sure before pointing at something.

**Comment by damianavila** [comment] 2017-06-13 00:08
Closing this one now, but please @jccardonar if you have further information, feel free to post it here so I can add it to the README later. Thanks in advance.

**Closed by damianavila** 2017-06-13 00:08 UTC
Labels: check
