### ISSUE TITLE
auto-select feature broken with an initial invisible 'skip' cell

### ISSUE THREAD

**Issue by miwojc** [damianavila/RISE#449] opened 2019-03-17 18:12 UTC
i have the below code in the notebook metadata:
```code
... 
 "livereveal": {
    "auto_select": "code",
    "autolaunch": true,
    "enable_chalkboard": true
  }
```
however when i press 'space' and new slide is displayed with cells with code, the cell with code is not selected. nothing happens when i press 'Shift + Enter", i need to select the cell with mouse click, only then i can run it with 'Shift + Enter".

Thanks!

**Comment by parmentelat** [comment] 2019-03-18 09:56
the settings in metadata look right (although it's recommended to use 'rise' instead of 'livereveal'); can you please provide your version numbers:

```bash
jupyter --version
jupyter notebook --version
python3 -c 'import rise; print(rise.__version__)'
```

have you done other notebook configuration, like in your .jupyter area ?

**Comment by miwojc** [comment] 2019-03-18 14:54
jupyter 4.4.0
jupyter notebook 5.7.4

python -c 'import rise; print(rise.__version__)'
gives me error: SyntaxError: EOL while scanning string literal

**Comment by parmentelat** [comment] 2019-03-18 15:04
the first 2 versions are fine  
how about using python3 as suggested ?

**Comment by miwojc** [comment] 2019-03-18 15:07
'python3' is not recognized as an internal or external command,

i have installed python via conda.

**Comment by parmentelat** [comment] 2019-03-18 15:20
I was just trying to make sure you're using the latest version that is 5.4.1
there has to be a way for you to find out what version of rise you are running  
maybe conda for one thing knows about that  

assuming it is the case:

your data suggests that the notebook configuration somehow gets overridden, since there are many different ways to change the default config  
if you're confortable with using your browser development console, the most effective way to troubleshoot this is probably to set a breakpoint at this line
https://github.com/damianavila/RISE/blob/07c0df8d5a3c96424ec673bbe5fc3bad62f9e228/rise/static/main.js#L144

and inspect the contents of complete_config, a javascript object that has an `auto_select` attribute; I suspect its value is not `code` as you are expecting it to be

**Comment by miwojc** [comment] 2019-03-18 17:19
rise version: 5.4.1

seems auto_select: 'code'

hmm?
![image](https://user-images.githubusercontent.com/32404415/54549448-5a507100-49aa-11e9-8fc5-cef5a0f41e74.png)

**Comment by parmentelat** [comment] 2019-03-18 17:37
huh; interesting; would you care to share the notebook and steps to reproduce, I'll see if it does the same in my setup, and if it does I should be able to shed some light on that.

**Comment by miwojc** [comment] 2019-03-18 17:57
sure, this is the notebook i cloned and locally installed Rise and changed notebook metadata.

https://github.com/datapythonista/demystifying_pandas_internals/blob/master/Demystifying%20pandas%20internals.ipynb

thank you!

**Comment by parmentelat** [comment] 2019-03-18 20:53
hello there

it appears that this slideshow has its first cell marked as 'skipped'  
as far as I can tell after a very short stab at this, that is a corner case that is poorly handled here

if that can help before the code can be fixed properly, marking this initial cell as a regular cell will repair the auto selection feature, at the price of a spurrious first cell;
and about that note that RISE does have a mechanism [for injecting css as explained here](https://rise.readthedocs.io/en/docs_hot_fixes/customize.html#adding-custom-css) but that's another matter entirely of course

**Comment by parmentelat** [comment] 2019-03-18 21:01
for the record: we don't impose the first cell to be marked 'slide', although it may be of course; we try to account for that, but in this corner case, first slide in the slideshow is computed as being #2, because the 'skip' attribute is not taken into account; so when translating a slide number into a cell index, current code is off by one slide; and selects a cell that is one earlier than the one on the screen

**Comment by miwojc** [comment] 2019-03-19 13:15
I changed first cell to "slide" and the cell with code was automatically selected so i could run it without a need to highlight the cell with mouse . Thanks for your help!

**Closed** 2019-04-11 08:14 UTC
Labels: Medium Priority, bug
