### ISSUE TITLE
Vertical Scrolling Issues

### ISSUE THREAD

**Issue by ChrisRackauckas** [damianavila/RISE#229] opened 2016-09-20 15:39 UTC
I used the command:

``` python
from traitlets.config.manager import BaseJSONConfigManager
path = "/home/crackauc/.jupyter/nbconfig"
cm = BaseJSONConfigManager(config_dir=path)
cm.update('livereveal', {
              'theme': 'sky',
              'transition': 'fade',
              'start_slideshow_at': 'selected',
                'width' : 1600,
                'height': 900,
                'scroll': True,
                'slideNumber': False,
})
```

to enable vertical scrolling. However, no scrollbar appeared. However, I can highlight and bring my curser to the bottom of the screen, causing it to scroll without using a scrollbar, meaning that in some sense scrolling got enabled (and the theme changed to sky, the transitions changed to fade, etc.).

My browser version is Chrome Version 53.0.2785.116 on CentOS7. Jupyter is being used through Julia (IJulia), and I am sure that the configuration file is correct (one because it's what Julia gives me as the config file, and secondly because all of the other changes occur).

**Comment by damianavila** [comment] 2016-09-21 12:34
Thanks for the report @ChrisRackauckas, I will try to reproduce with your browser version...

**Comment by damianavila** [comment] 2017-06-13 00:09
Vertical scrolling was re-done in the latest release. It is working as expected now. Closing here.

**Closed by damianavila** 2017-06-13 00:09 UTC
Labels: bug, High Priority

**Comment by ChrisRackauckas** [comment] 2017-06-15 19:13
Thanks! Perfect timing!

**Comment by ChrisRackauckas** [comment] 2017-06-15 19:28
I am assuming this didn't make it into 5.0?

**Comment by damianavila** [comment] 2017-06-15 20:42
@ChrisRackauckas yes, it is part of 5.0... are you activating the scrolling option? Because it is False by default, ref here: https://github.com/damianavila/RISE#configure-your-own-options

**Comment by j3mdamas** [comment] 2018-02-19 17:50
@damianavila the scroll function was just what I was looking for, amazing!
