### ISSUE TITLE
Configuration in notebook metadata has no effect

### ISSUE THREAD

**Issue by jluttine** [damianavila/RISE#195] opened 2016-06-15 16:46 UTC
I followed the instructions mentioned here:

https://github.com/damianavila/RISE#alternative-configuration-method

But livereveal settings in the metadata have no effect. I tried closing and re-opening the notebook, but doesn't help. Neither does shutting down the notebook and re-opening.

My full metadata:
```
{
  "livereveal": {
    "theme": "night",
    "transition": "zoom",
    "width": 1900,
    "height": 1000
  },
  "kernelspec": {
    "name": "python3",
    "display_name": "Python 3",
    "language": "python"
  },
  "celltoolbar": "Slideshow",
  "language_info": {
    "mimetype": "text/x-python",
    "version": "3.5.1",
    "pygments_lexer": "ipython3",
    "name": "python",
    "nbconvert_exporter": "python",
    "codemirror_mode": {
      "version": 3,
      "name": "ipython"
    },
    "file_extension": ".py"
  }
}
```

**Comment by hkarl** [comment] 2016-07-05 06:49
Similar effect here. Configuration: 


* jupyter 4.1.0   (pip only sees this version ?)
* python 3.51
* ipython 4.2.1
* no conda, just pip
* RISE cloned from github
* markup ignored by firefox, chrome, safari 

Although other people are able to get it work, see here: https://groups.google.com/d/msgid/jupyter/5dfc73bc-b9b8-45c0-9004-e75d4c8adb27%40googlegroups.com?utm_medium=email&utm_source=footer&r=anVweXRlckBnb29nbGVncm91cHMuY29t 

Perhaps a jupyter version issue? 

Thanks 

Holger

**Comment by damianavila** [comment] 2016-07-12 14:05
This is a duplicate of #172.
Continuing the discussion there, closing here.

**Closed by damianavila** 2016-07-12 14:05 UTC
