### ISSUE TITLE
Return to current cell in notebook mode

### ISSUE THREAD

**Issue by mjbright** [damianavila/RISE#154] opened 2015-10-10 08:23 UTC
There is a configuration element to start a slideshow from the current cell.

However when leaving slideshow mode the notebook always returns to the first cell of the notebook.
It should be a configurable to stay at the current cell.

**Comment by damianavila** [comment] 2015-10-12 21:53
Duplicate of #102, closing here...

**Closed by damianavila** 2015-10-12 21:53 UTC
