### ISSUE TITLE
There are no buttons and only alt+r hotkey is working.

### ISSUE THREAD

**Issue by soerendip** [damianavila/RISE#468] opened 2019-04-26 18:14 UTC
I installed the extension with conda and updated jupyter and notebook. Now, using notebook 5.7.8.
There is a toggle button that switches to the slide show, but the whole notebook is shown. There is no option to define new slides or subslides. In the console I get rise.css not found. I tried creating a new notebook.

**Comment by damianavila** [comment] 2019-04-26 19:46
>There is no option to define new slides or subslides.

Did you follow these instructions? https://rise.readthedocs.io/en/docs_hot_fixes/usage.html#creating-a-slideshow

I mean, did you have access to the Cell Toolbar? And selected the Slideshow option?

**Comment by Kaasstengel** [comment] 2019-06-12 12:55
Similar issue here, although I have used pip to install RISE. I don't seem to be able to start a slideshow, I do have access to the toolbar to select the slideshow option. 

p.s. the link you sent does not seem to be working @damianavila

**Comment by parmentelat** [comment] 2019-06-12 15:47
hi, the correct link is

https://rise.readthedocs.io/en/stable/usage.html?highlight=menu#creating-a-slideshow

so, just to be clear, the expected behaviour is this:

* you install rise through pip
* you restart your jupyter notebook server if needed
* when opening a notebook, you should see an additional button in the menubar, that lets you start the slideshow; that is **the only visible difference**

* if you need to enable the cell menubar for marking cells as slide or subslide or what not, you need to do this explicitly, this is not automatically done by rise in any way - and it would be wrong because of the other kind of cell toolbars available

* as far as keyboard shortcuts are concerned, installing rise is indeed expected to bind 'Alt-r' to start and quit the slideshow; (because the slideshow takes all the space, the menubar button is no longer visible in slideshow mode, so you can use a clickable overlay x-shaped button to quit slideshow mode)

that's about it

I'm not quite sure that what you are reporting is not the expected behaviour; please post a screenshot if you are unsure

**Comment by parmentelat** [comment] 2019-06-20 18:34
My understanding is that the behaviour reported by @soerendip  and @Kaasstengel is the expected behaviour

however it is my feeling also that we could greatly improve user's experience if we were to somehow help newcomers find their way faster; it is bit very intuitive to have to go so deep in the menus to enable the slideshow toolbar

we could add another button - close to the one that starts a slideshow - to enable that cell toolbar

or even better, we could just enable that toolbar upon loading of rise; I'm less comfortable about that one: for it not be too intrusive we could agree to enable that toolbar only if no toolbar is already selected; but we can do that only when we're sure that all extensions have been loaded, which I'm not quite sure how to do properly

mostly thinking aloud here, any other thoughts here ?

**Comment by damianavila** [comment] 2019-06-27 13:13
> however it is my feeling also that we could greatly improve user's experience if we were to somehow help newcomers find their way faster; it is bit very intuitive to have to go so deep in the menus to enable the slideshow toolbar

I agree.

> we could add another button - close to the one that starts a slideshow - to enable that cell toolbar

That's an interesting idea...

> or even better, we could just enable that toolbar upon loading of rise;

too intrusive, I think...

**Comment by tobycheese** [comment] 2019-10-21 15:44
I just noticed that while my button shows on Chrome, it is not there when I open the same notebook ind the same virtualenv with Safari. I don't have any time to look into this right now (I am preparing a talk :-)), but maybe I can later.

**Comment by parmentelat** [comment] 2019-10-21 15:49
Hello
As pointed out in a few other issues, I suggest for you to install the 5.6 dev release 

`pip install —pre -U rise`

A major flaw, that has to do with other extensions being installed and conflicting in terms of keyboard shortcuts, has been fixed in this release

**Comment by damianavila** [comment] 2019-11-08 13:07
@soerendip, @Kaasstengel, I will be releasing the new version this weekend, so you will have a fix available by next week if you are willing to upgrade.

**Comment by kurtmckee** [comment] 2021-01-07 04:23
Could this issue be closed? It appears that a new RISE version was released and perhaps this could be closed?

**Comment by parmentelat** [comment] 2021-01-08 09:54
indeed

**Closed by parmentelat** 2021-01-08 09:54 UTC
Labels: more-input-needed, question
