### ISSUE TITLE
I can install Jupyter

### ISSUE THREAD

**Issue by elMor3no** [damianavila/RISE#142] opened 2015-09-05 14:56 UTC
all the time i try to install:

$ python setup.py install

 i get:
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from notebook.nbextensions import install_nbextension
ImportError: No module named 'notebook'

What i making wrong?

**Comment by damianavila** [comment] 2015-09-05 17:24
you need to have Jupyter 4.0 or above you probably have IPython 3.x version installed

**Comment by elMor3no** [comment] 2015-09-05 18:56
I have Python 2.7.9 and Python3.4 installed

I made all of this:

$ sudo apt-get install python3-pip
$ sudo pip3 install --upgrade "notebook"
$ jupyter nbextension install
$ python3 setup.py install

And the result is:
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    main()
  File "setup.py", line 34, in main
    enable=(not args.no_enable))
  File "setup.py", line 14, in install
    cm.update('notebook', {"load_extensions": {"livereveal/main": True}})
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/manager.py", line 87, in update
    self.set(section_name, data)
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/manager.py", line 71, in set
    self.ensure_config_dir_exists()
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/manager.py", line 46, in ensure_config_dir_exists
    os.mkdir(self.config_dir, 0o755)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pablo/.jupyter/nbconfig'

**Comment by damianavila** [comment] 2015-09-08 10:27
I think the problem is the mix of a system-wide installation and the local one on RISE.

Can you try this? (not using sudo)

`pip3 install notebook`

and then

`python3 setup.py install`

Let me see if you see any errors...

**Comment by laowantong** [comment] 2015-09-15 12:02
I had the same error as _elMor3no_ on a fresh Anaconda installation. The following worked for me:

    pip install notebook
    jupyter notebook
    python setup.py install

The second command was needed to create the folder `~/.jupyter/nbconfig`.

**Comment by damianavila** [comment] 2015-09-16 14:14
@laowantong that's interesting... keeping opened until I check this is still the case on the latest release...

**Comment by nicktimko** [comment] 2015-10-08 23:37
Related: https://github.com/ipython/traitlets/pull/93

**Comment by damianavila** [comment] 2015-10-09 11:57
Yep, I think we can close this one...

**Closed by damianavila** 2015-10-09 11:57 UTC
Labels: discussion
