### ISSUE TITLE
pip installable package?

### ISSUE THREAD

**Issue by AlJohri** [damianavila/RISE#187] opened 2016-03-19 09:02 UTC
> With Jupyter landing we will provide a conda and pip-instalable packages too

Was wondering if there was any update on creating a pip installable package? I see there was an attempt made on #147 by @akaihola

Perhaps you can look at the `nbgrader` package? I found their command line tool to enable and disable the extension quite useful.

https://nbgrader.readthedocs.org/en/latest/user_guide/installation.html

- `pip install nbgrader`
- `nbgrader extension install`
- `nbgrader extension activate`

This may alleviate issues such as #178

**Comment by damianavila** [comment] 2016-03-19 19:00
I started a branch to make RISE pip installable some time ago but never got enough time to finish it... I will try to recover the work in the following days, thanks for remind me about this again :wink:

**Comment by jrderuiter** [comment] 2016-04-12 08:34
Would also like this!

**Comment by damianavila** [comment] 2016-07-11 22:07
This is a duplicate of #146, closing here and continue the discussion there...

**Closed by damianavila** 2016-07-11 22:07 UTC
Labels: enhancement, High Priority
