### ISSUE TITLE
down-button won't go into subslides

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#180] opened 2016-02-04 15:06 UTC
Hi there; 

I just ran into a small glitch, I can use left- and right- buttons on my keyboard to navigate in slides, but on a slide that has subslides I cannot use down-button to see them
The down arrow in the navigator is shown as active (I mean it's not greyed out), and I can use the mouse and click it, but from the keyboard, nope; up-button won't work either to come back up.

What can I be doing wrong here ? 

again this is a very exciting tool, thanks !!

**Comment by parmentelat** [comment] 2016-02-04 15:10
I just realized that up and down are bound to moving in cells.. 
Just tried some modifier keys like Control-down and Shift-down, to no avail either
and Alt-down on my mac is bound to mission-control thingy
What's the expected behaviour ?

**Comment by nehalecky** [comment] 2016-02-04 17:57
I've also been experiencing this, and believe it might be related to the the new release of Jupyter (`4.1.0`)—what version are you using? Seems like there were a few other regressions in RISE functionality since that release.

**Comment by parmentelat** [comment] 2016-02-04 18:55
```
$ jupyter --version
4.0.6
```

I guess I was confused mostly because I had been browsing this 
http://bollwyvl.github.io/live_reveal/#/
where I discovered about subslides, and in this presentation the down button was working fine.

Can someone please state what the expected behaviour is ?

**Comment by damianavila** [comment] 2016-02-04 23:08
There were other's report about some keyboard not working OK, I will take a look in the next few days...

**Comment by mihailupu** [comment] 2016-03-01 16:01
hi,
for me the button-down/up works with FN (Mac keyboard), as i read somewhere that subslides are changed with PgUp/PgDn and that's the combination necessary for these on my keyboard in the absence of these physical keys.

I had another issue with keyboard shortcuts: Shift+Enter does not work while in slideshow mode, nor after exiting it. After exiting it, I can get it to work again if i remove from the URL the parameters (everything after the \# sign following the ipynb extension)

**Comment by damianavila** [comment] 2016-03-15 20:24
Sorry, I was on vacation, I will try to look into this soon...

**Comment by ianhbell** [comment] 2016-04-28 00:29
I confirm that on windows page up/down go into subslides, but up/down do not.

**Comment by ibell** [comment] 2016-04-28 05:03
Also, Esc seems to no longer do the overview

**Comment by damianavila** [comment] 2016-04-28 13:29
Yes, all the shortcuts need a revision because of the latest changes in the notebook.
Still struggling to have some time for work on this fixes... sorry about the delay...

**Comment by damianavila** [comment] 2016-07-11 22:47
`pgup` and `pgdn` are working as expected... as it is stated in the README the up/down keys are to move between cells... 

Additionally all the RISE keys are working in master now:

Reveal Shortcuts Help
* Alt+r: Enter/Exit RISE
* w: Toggle overview mode
* ,: Toggle help and exit buttons
* Home: First slide
* End: Last slide
* space: Next
* Shift+space: Previous
* PgUp: Up
* PgDn: Down
* left: Left
* right: Right
* . or /: black screen
NOTE: You have to use these shortcuts in command mode.

Closing this one now.

**Closed by damianavila** 2016-07-11 22:47 UTC
Labels: bug, check, High Priority

**Comment by Spaxe** [comment] 2017-08-03 05:46
I'd like to raise a usability issue, at least for people on MacOS (bear with me).

To access PgUp/PgDn, on the MacBooks, you press Fn + Up / Fn + Down. (I assume this is also the case for some others.)

However, Fn + Left / Fn + Right emits Home / End, which skips the slides to the beginning or end.

So you have this disparity in controls, when you hold down Fn key, the behaviours in arrows are very different.

Here's a proposal:

* Alt + Left: Previous Slide
* Alt + Right: Next Slide
* Alt + Up: Previous Sub-Slide
* Alt + Down: Next Sub-Slide

Essentially - the control would be the same as Reveal.js, but with a modifier. The experience will be a lot smoother for the presenters. No more Fn key confusion.

**Comment by damianavila** [comment] 2017-08-04 12:43
I think it is a good suggestion... can you open a new issue with the previous message you I can label it as enhancement and assign some priority? Thanks!

**Comment by Spaxe** [comment] 2017-08-04 12:55
Will do 😊 I'm still trying to work out how this will work with wireless presenter clickers, but one thing at at time

**Comment by damianavila** [comment] 2017-08-04 13:21
> Will do :blush: I'm still trying to work out how this will work with wireless presenter clickers, but one thing at at time

AFAIK, reveal.js supports wireless presenters, so we can investigate how to make that easier on RISE... open an issue for that with your thoughts to discuss. Thanks!

**Comment by gtolomei** [comment] 2017-09-06 17:32
Hi,

I'm really interested in what @Spaxe was investigating, i.e., how RISE works in combination with wireless remote clickers/pointers? I guess everything should be fine when moving from one slide to the next/previous (which corresponds to pressing Right -> and Left <- keys) but what about "simulating" PgUp and PgDown for moving from/to sub-slide to/from slide (i.e., what about Fn + Up and Fn + Down)?
Also, any updates on @Spaxe's proposal about changing the shortcut using Alt as modifier?

Many Thanks,
Gabriele

**Comment by Spaxe** [comment] 2017-09-06 22:59
Hi @gtolomei, please go to #278 for discussing this proposal.

I'm going to buy myself a clicker soon (phone died so my plans have been postponed), and try this out.

**Comment by gtolomei** [comment] 2017-09-07 06:44
Thanks @Spaxe!

**Comment by damianavila** [comment] 2017-09-08 13:21
> how RISE works in combination with wireless remote clickers/pointers?

I have seen a remote wireless working with RISE, so it is definitely possible. Maybe there is some tiny things to fix to make it very pleasant but we can always work that out.

**Comment by damianavila** [comment] 2017-09-08 13:22
> what about "simulating" PgUp and PgDown for moving from/to sub-slide to/from slide (i.e., what about Fn + Up and Fn + Down)?

That a good question, but I do not have a remote controller at hand to test... I guess it is just a matter of configuration and maybe some changes in the keys at the RISE level as discussed by @Spaxe.
