### ISSUE TITLE
not working within Julia?

### ISSUE THREAD

**Issue by bradleyashton** [damianavila/RISE#249] opened 2017-03-27 03:13 UTC
If I run `jupyter` from the command line the slideshow button is available and works, but without interactive support for things like @manipulate that I am used to using in `Julia`

If I launch `jupyter` from within `Julia`, then there is no slideshow button. Have I installed this correctly? I can't figure out how to install it for `Julia` directly. I had to install a separate `miniconda3` to get `jupyter` going from the command line. 

Thanks for any help

**Comment by damianavila** [comment] 2017-03-27 19:17
Interesting... I never try it on Julia... in principle, it should work because this is a JS thing... so if should not affect if you are using a Python or Julia kernel... Can you give me some details to try to reproduce the issue? Thanks!

**Comment by znmeb** [comment] 2017-03-27 19:56
I'm in the middle of building a Docker image with Jupyter, R, Python3 and Julia. It's not quite baked yet but in the process I gave up very early on trying to use the Julia / IJulia "embedded Conda" for anything. The main issue is the lack of ability to customize how the notebook is started.

Then I gave up on Anaconda and Miniconda because the resulting Docker image was too big. So that left installing all the notebook stuff with virtualenvwrapper / pip and I have that mostly working. If you want to follow along it's at https://github.com/znmeb/DFS-Analytics-Toolbox. It's got "nbpresent" at the moment but I'm planning to add RISE as soon as everything else is working.

**Comment by bradleyashton** [comment] 2017-03-27 21:12
Ok, so this is probably just me not understanding the Python environment very well. 

There are two issues here
1. Are there any julia-specific installation instructions for rise?  
Julia uses its own embedded version of `miniconda`, so there is probably some special install I should do. At the moment I just don't have a slideshow button in julia/jupyter, and I have no idea how to get one. This version of jupyter is launched from a `julia` session via
```julia
julia> using IJulia

julia> notebook()
```
2. If I install a separate `miniconda` and use that to install rise via `pip`I launch jupyter from the command line using
```bash
dirac:~ abradley$ jupyter notebook
```
and then I get the slideshow button in jupyter, but some of the interactivity doesn't initiate in slideshow mode. In particular, the `@manipulate` macro from package `Interact` doesn't work properly. Instead it just produces the default result for the code block, and no slider appears. Anyone figured out how to get this enabled in jupyter from the command line?

**Comment by znmeb** [comment] 2017-03-27 21:39
You probably want to look at the IJulia install instructions: https://github.com/JuliaLang/IJulia.jl#installation

First, you install Anaconda or Miniconda and make a notebook environment. Then add RISE to that. You should have a working notebook with RISE at this point.

Then, in a command window, set the JUPYTER environment variable to wherever the "jupyter" executable landed in the build. On my Linux box it's `~/miniconda3/envs/julia/bin/jupyter`. Once you have that variable set, start up Julia and do `Pkg.add("IJulia")`. If the environment variable is correct, Julia will use your notebook and not build it's own with its embedded Conda.

**Comment by bradleyashton** [comment] 2017-03-27 22:41
Ok, since I had a functioning version with RISE added to it, I then opened julia and pointed the package manager to my other version of jupyter:

```julia
julia> Pkg.rm("IJulia")
julia> Pkg.update()
julia> ENV["JUPYTER"]="/Users/abradley/miniconda3/bin/jupyter"
"/Users/abradley/miniconda3/bin/jupyter"
julia> Pkg.add("Julia")
```
Everything builds happily, but when I 
```julia
julia> using IJulia
INFO: Recompiling stale cache file /Users/abradley/.julia/lib/v0.5/IJulia.ji for module IJulia.

julia> notebook()
```
I get the same issue as I had previously when running the notebook from the command line: slideshow mode is available and runs (already progress here!), but interactivity is still disabled (no sliders).

Since it is now working in `julia` in the same way, maybe this points to a RISE issue?

**Comment by znmeb** [comment] 2017-03-27 23:39
Hmm ... I'm not a Python programmer but it looks like your environment is missing a module or two or you may need to run / rerun a `jupyter nbextension install` step.

**Comment by znmeb** [comment] 2017-03-28 00:06
OK - I think I have it running with `virtualenvwrapper`! Here's the sequence:

```
source $VIRTUALENVWRAPPER_SCRIPT \
  && mkvirtualenv --python=/usr/bin/python3 julia \
  && pip3 install jupyter nbpresent ipyparallel RISE \
  && jupyter nbextension install nbpresent --py --overwrite --user \
  && jupyter nbextension enable nbpresent --py --user \
  && jupyter serverextension enable nbpresent --py \
  && ipcluster nbextension enable --user \
  && jupyter nbextension install rise --py --overwrite --user \
  && jupyter nbextension enable rise --py --user \
  && julia -e 'Pkg.add("IJulia")' \
  && echo "source $VIRTUALENVWRAPPER_SCRIPT" >> ~/.bashrc \
  && echo "export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python" >> ~/.bashrc 
```

That gives me a notebook with
* IPython Cluster tab working
* RISE widgets
* nbpresent widgets
* both Python 3 and Julia kernels

**Comment by bradleyashton** [comment] 2017-03-28 01:35
this seems to lead down a deep rabbit hole involving getting a properly linked and setup `virtualenvwrapper` installed... I haven't made it out yet ...

**Comment by bradleyashton** [comment] 2017-03-28 02:06
great! As a newbie, I also went here:

http://joebergantine.com/blog/2015/apr/30/installing-python-2-and-python-3-alongside-each-ot/

to get `virtualenv` running

**Closed** 2017-04-27 08:26 UTC
Labels: discussion
